version: '3.9'

services:
  simplonapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springmysql-net

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: always
    command: --bind-address=0.0.0.0

    environment:
      MYSQL_DATABASE: simplon
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ultimatum
      MYSQL_PASSWORD: ultimatum
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springmysql-net

networks:
  springmysql-net:

volumes:
  mysql_data:
