spring:
    datasource: 
        url: jdbc:mysql://mysqldb:3306/simplon
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

        

