name: Build and publish a Docker image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"
 

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.IMG_NAME }}:${{ steps.metadata.outputs.tags }}
          docker push ${{ env.IMG_NAME }}:${{ steps.metadata.outputs.tags }}
