name: Java CI/CD with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout #qui signifie que l'on va récupérer le code source de notre projet 
     uses: actions/checkout@v3 #on utilise l'action checkout@v3 qui permet de récupérer le code source de notre projet
    - name: Build and push docker images #on va construire notre image docker et la pousser sur dockerhub
      uses: mr-smithers-excellent/docker-build-push@v5 #on utilise l'action docker-build-push@v5 qui est un modele predefini pour construire et pousser une image docker
      with:
        registry: docker.io #on indique que l'on va pousser notre image sur dockerhub
        image: hultimatum/ci-cd-simplon #on indique le nom de notre image
        tags: latest #on indique le tag de notre image
        dockerfile: Dockerfile #on indique le nom de notre fichier dockerfile
        username:  ${{ secrets.DOCKERHUB_USERNAME }} #on indique le nom d'utilisateur de notre compte dockerhub
        password: ${{ secrets.DOCKERHUB_PASSWORD }} #on indique le mot de passe de notre compte dockerhub
    
   



        